typography_spectrum: 0.7706093
color:
  saturation: 0.8566308
  brandStrength: 0
  lightness: 0.688172
  brandColors:
    - '#0E0F11'
    - '#586D88'
    - '#FFCEA6'
    - '#A4A8AB'
    - '#433E42'
  rhythmicContrast: 0.8835126
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  twitter: null
  google: null
  facebook: null
name: plan | b agentur für massnahmen ag
cta:
  bucket: null
  version: null
  domain: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Multidisziplinär
description: 'Konzepte, Design, Texte'
purpose: []
